Refactor
It should be easily maintainable now.

diff --git a/hyprshotgun b/hyprshotgun
--- a/hyprshotgun
+++ b/hyprshotgun
@@ -2,79 +2,101 @@
 # Screenshot helper for hyprland.
 # Copyright 2023, Adrian Lopez.
 
+
+# CHECK WAYLAND SESSION
+# ======================================
+if [ -z $WAYLAND_DISPLAY ]; then
+	(>&2 echo Wayland is not running)
+	exit 1
+fi
+
+
+# PARSE CONFIG FILE
+# ======================================
+if [ -f ~/.config/hyprshotgun.sh ]; then
+	. ~/.config/hyprshotgun.conf
+fi
+if [ -z $HYPRSHOTGUN_SCREENSHOTS ]; then
+	HYPRSHOTGUN_SCREENSHOTS=$(xdg-user-dir PICTURES)
+fi
+
+
 # CONSTANTS
 # ======================================
 SCREENSHOT_TIMESTAMP=$(date "+${HYPRSHOTGUN_DATEFMT:-%F_%H-%M-%S_%N}")
 SCREENSHOT_FULLNAME="$HYPRSHOTGUN_SCREENSHOTS"/screenshot_${SCREENSHOT_TIMESTAMP}.png
 
 
-# CHECKS
+# HELPER METHODS
 # ======================================
-if [ -z $WAYLAND_DISPLAY ]; then
-  (>&2 echo Wayland is not running)
-  exit 1
-fi
+display_help(){
+      GREEN='\033[32m'
+      YELLOW='\033[33m'
+      RED='\033[31m'
+      CYAN='\033[36m'
+      RESET='\033[0m'
 
+      echo -e "$GREEN# HOW TO USE$RESET"
+      echo -e ""$YELLOW"===================$RESET"
+      echo -e "$RED*$RESET Local screenshot:"
+      echo -e "hyprshotgun $CYAN[display|window|region|alldisplays]$RESET"
+      echo "" 
+      echo -e "$RED*$RESET Online screenshot:"
+			echo -e "hyprshotgun $CYAN[display|window|region|alldisplays]$RESET upload"
+      echo ""
+      echo ""
+      echo -e "$GREEN# ADVANCED SETTINGS$RESET"
+      echo -e "$YELLOW===================$RESET"
+      echo -e "$RED*$RESET Change the screenshot directory (optional):"
+			echo 'By default, the screenshots are saved in $XDG_PICTURES_DIR. You can choose a different directory by setting the env var $HYPRSHOTGUN_SCREENSHOTS="/my/screenshot/directory/". Alternatively, you can export that same env var inside the config file ".config/.hyprshotgun.conf".'
+      echo
+}
 
-# CONFIGURATION
-# ======================================
-## Put the path to your own screenshot folder
-## to variable HYPRSHOTGUN_SCREENSHOTS here: ~/.config/hyprshotgun.conf
-if [ -f ~/.config/hyprshotgun.sh ]; then
-	. ~/.config/hyprshotgun.conf
-fi
-
-if [ -z $HYPRSHOTGUN_SCREENSHOTS ]; then
-	HYPRSHOTGUN_SCREENSHOTS=$(xdg-user-dir PICTURES)
-fi
-
-
-# DEFINE HELPERS
-# ======================================
-readonly filter='
-# returns the focused node by recursively traversing the node tree
-def find_focused_node:
-    if .focused then . else (if .nodes then (.nodes | .[] | find_focused_node) else empty end) end;
-# returns a string in the format that grim expects
-def format_rect:
-    "\(.rect.x),\(.rect.y) \(.rect.width)x\(.rect.height)";
-find_focused_node | format_rect
-'
-
-make_screenshot() {
+take_screenshot() {
 	case "$1" in
 		-h|--help)
-
-      echo '* NORMAL USAGE:'
-      echo '-----------------'
-      echo '* Local screenshot:'
-      echo 'hyprshotgun [display|window|region|alldisplays]'
-      echo '' 
-      echo '* Online screenshot:'
-			echo 'Usage: hyprshotgun [display|window|region|alldisplays] upload'
-      echo ''
-      echo '* ADVANCED:'
-      echo '-----------------'
-      echo 'Changing screenshot directory:'
-			echo 'By default the screenshots are saved in XDG_PICTURES_DIR. You can choose a different directory by setting the env: HYPRSHOTGUN_SCREENSHOTS="/my/screenshot/directory/" Alternatively, you can put it on .config/.hyprshotgun.conf'
-
+      display_help
 			return 0
 			;;
 		region)
-      grimblast copysave area "$2"
+      grimblast save area "$2"
 			;;
 		window)
-      grimblast copysave active "$2"
+      grimblast save active "$2"
 			;;
 		alldisplays)
-      grimblast copysave screen "$2"
+      grimblast save screen "$2"
+      ;;
+		display)
+			grimblast save output "$2"
       ;;
 		*)
-			grimblast copysave output "$2"
+      echo "Invalid argument:"
+      echo ""
+      display_help
+      return 0
       ;;
+
 	esac
 }
 
+upload_screenshot(){
+  # If there is not screenshot file, then there is nothing to upload
+  if [ ! -f "$SCREENSHOT_FULLNAME" ]; then exit; fi
+
+  # Upload
+  case "$1" in
+    upload)
+      # If curl exist, use it to upload the image to 0x0
+      if type curl >/dev/null  2>&1; then
+        SCREENSHOT_LOCATOR=$(curl -s -F "file=@\"$SCREENSHOT_FULLNAME\";filename=.png" 'https://0x0.st')
+		  fi
+      ;;
+   esac
+}
+
+# We support wl-copy, xsel, and xclip.
+# The first one found by order of priority will be used.
 copy_to_clipboard() {
 	if type wl-copy >/dev/null  2>&1; then
 		if [ -z $HYPRSHOTGUN_WL_COPY_FILE ]; then
@@ -93,55 +115,34 @@ copy_to_clipboard() {
 	fi
 }
 
-show_message() {
+# Wrapper method for notify-send
+send_notification() {
 	if type notify-send >/dev/null  2>&1; then
 		notify-send --expire-time=3000 --category=screenshot --icon="$2" "$3" "$1"
 	fi
 }
 
-upload_screenshot() {
-	if [ -f "$1" ]; then
-		if type curl >/dev/null  2>&1; then
-			curl -s -F "file=@\"$1\";filename=.png" 'https://0x0.st'
-		fi
-	fi
+# The actual notification we show
+show_notification(){
+  case "$1" in
+    upload)
+      if [ -z $SCREENSHOT_LOCATOR ]; then
+        copy_to_clipboard "$SCREENSHOT_FULLNAME"
+        send_notification "$SCREENSHOT_FULLNAME" document-save "Online screenshots are not available at the moment. Local path copied to the clipboard instead:"
+      else
+        copy_to_clipboard "$SCREENSHOT_LOCATOR"
+        send_notification "$SCREENSHOT_LOCATOR" document-send "URL copied to the clipboard:"
+      fi
+      ;;
+    *)
+      copy_to_clipboard "$SCREENSHOT_FULLNAME"
+      send_notification "$SCREENSHOT_FULLNAME" document-save "Path copied to the clipboard:"
+  esac
 }
 
 
-# ENTRY POINT
+# ENTRY POINT OF THE PROGRAM
 # ======================================
-make_screenshot "$1" "$SCREENSHOT_FULLNAME"
-if [ ! -f "$SCREENSHOT_FULLNAME" ]; then
-	exit;
-fi
-
-
-# UPLOAD (TODO: We shold make a method here and just call it in the entry poing)
-# ======================================
-# If the parameter "upload" is passed, 
-# upload to the cloud
-
-case "$2" in
-	upload)
-		SCREENSHOT_LOCATOR=$(upload_screenshot "$SCREENSHOT_FULLNAME")
-		if [ -z $SCREENSHOT_LOCATOR ]; then
-			copy_to_clipboard "$SCREENSHOT_FULLNAME"
-			show_message "$SCREENSHOT_FULLNAME" document-save "Screenshot path"
-			if [ ! -z $HYPRSHOTGUN_WL_COPY_FILE ]; then
-				show_message "Screenshot was copied to clipboard.\\nFeel free to paste it." "$SCREENSHOT_FULLNAME" "Screenshot image"
-			fi
-		else
-			copy_to_clipboard "$SCREENSHOT_LOCATOR"
-			show_message "$SCREENSHOT_LOCATOR" document-send "Screenshot URL"
-			if [ ! -z $HYPRSHOTGUN_WL_COPY_FILE ]; then
-				show_message "Screenshot was copied to clipboard.\\nFeel free to paste it." "$SCREENSHOT_FULLNAME" "Screenshot image"
-			fi
-		fi
-		;;
-	*)
-		copy_to_clipboard "$SCREENSHOT_FULLNAME"
-		show_message "$SCREENSHOT_FULLNAME" document-save "Screenshot path"
-		if [ ! -z $HYPRSHOTGUN_WL_COPY_FILE ]; then
-			show_message "Screenshot was copied to clipboard.\\nFeel free to paste it." "$SCREENSHOT_FULLNAME" "Screenshot image"
-		fi
-esac
+take_screenshot "$1" "$SCREENSHOT_FULLNAME"
+upload_screenshot "$2"
+show_notification "$2"
